Name: datasets
DATASET:
  Source_data_root: datasets/source_data.csv
  Source_label_root: datasets/source_label.csv
  Source_adj_root: datasets/source_adj.csv
  target_data_root: datasets/target_data.csv
  target_label_root: datasets/target_label.csv
  target_adj_root: datasets/target_adj.csv
MODEL:
  NAME: tf_model
  INPUT_DIM: 6922
  Conv: TransformerConv
  Feature_extractor: [128,16]
  num_classes: 2
TRAIN:
  lr: 0.001000
  Epochs: 10
  Save_path: ./checkpoint
  Momentum: 0.999000
  Weight_decay: 0.000100
  grad_clip: 5
TEST:
  Save_path: ./checkpoint/best_loss.pth
  Pred: ./results
  Verbose: 0
SEED: 42
Use_CUDA: True
